// Generated by  : ImageConverter 565 v2.2
// Generated from: ore.png
// Time generated: 15/12/2020 14:00:41
// Dimensions    : 3x3 pixels
// Size          : 18 Bytes

#include <avr/pgmspace.h>

const unsigned short oreIcon[0x09] PROGMEM ={

		0xFA00, 0xFDE0, 0xFC00, 0xFDE0, 0xFDE0, 0xFC00, 0x0000, 0xFC00, 0xFC00, };
